### ISSUE TITLE
sample_id not passed to aggregate

### ISSUE THREAD

**Issue by bkellman** [matsengrp/phip-flow#74] opened 2024-06-27 14:36 UTC
Aggregation only works for sample_ID but for other grouped variables it is failing:

```
                  if d.shape[0] > 0
                  for k, v in [
                      (f"n_hits_{label}", (d["hit"] == "TRUE").sum()),
                      (f"n_discordant_{label}", (d["hit"] == "DISCORDANT").sum()),
                      (f"n_edgeR_hits_{label}", (d["edgeR_hit"] == "TRUE").sum()),
                      (f"n_edgeR_discordant_{label}", (d["edgeR_hit"] == "DISCORDANT").sum()),
                      (f"max_ebs_{label}", d["EBS"].max()),
                      (f"mean_ebs_{label}", d["EBS"].mean())
                  ]
                  if k not in ["n_hits_hits", "n_discordant_hits"]
              }
          }])

          return dat


  AggregatePhIP()

Command exit status:
  1

Command output:
  (empty)

Command error:
    File ".command.sh", line 103
      self.organism_table.to_csv(""".organism.summary.csv.gz", index=None)
                                                            ^
  SyntaxError: unterminated string literal (detected at line 103)

```

I think it may be related to this line:
https://github.com/matsengrp/phip-flow/blob/0a36357f4369bdd3919e33f8a6458c2577693f96/templates/aggregate_organisms.py#L103

and a possible failure of sample_id to be passed to that line.

Below is the slurm call
```
#!/bin/bash
#SBATCH -c 20                               # Request one core
#SBATCH -t 3-00:05                         # Runtime in D-HH:MM format
#SBATCH -p medium                           # Partition to run in
#SBATCH --mem=100G                         # Memory total in MiB (for all cores)
#SBATCH -o momi_p1_%j.out                 # File to which STDOUT will be written, including job ID (%j)
#SBATCH -e momi_p1_%j.err                 # File to which STDERR will be written, including job ID (%j)
                                           # You can change the filenames given with -o and -e to any filenames you'd like

source /home/${USER}/.bashrc
source activate phipflow2

basedir=/n/scratch/users/b/bek321/virscan_hipc/20240214_HIPC_MOMI_vircan_allplate/
scratchdir=/n/scratch/users/b/bek321/virscan_hipc/20240214_HIPC_MOMI_vircan_allplate/
cr=50
hd=17
SAMPLES=../data-raw/20240216_momi_virscan_allplate_merged_metadata.csv
PEP=../data-raw/peptide_tables/VIR3_clean_CMVFixed_n_Betacoronavirus1.csv


cd ${basedir}data-final

for group in sample_ID Timepointsimple F.Sex
do
        nextflow run matsengrp/phip-flow -r V1.12  \
                --sample_table $SAMPLES \
                --peptide_table $PEP \
                --read_length 50 --oligo_tile_length 168 \
                --run_zscore_fit_predict true \
                --run_cpm_enr_workflow true \
                --summarize_by_organism true \
                --output_wide_csv true \
                --output_tall_csv false \
                --run_BEER false \
                --peptide_seq_col peptide \
                --peptide_org_col Species \
                --sample_grouping_col $group \
                --results 20240216_momi_plate${FC}.${group}.Species."$(date -I)" \
                -resume

done

```

**Comment by bkellman** [comment] 2024-06-27 14:37
Also, I checked and there are no invalid sample_IDs in the sample ID column

**Comment by jgallowa07** [comment] 2024-07-15 15:07
Sorry for the late follow-up here @bkellman. Looking into this today

**Comment by bkellman** [comment] 2024-07-15 17:07
Awesome! The issue can occur when sample_ID (non-unique) is mislabeled as the replicate (unique). But I also observed this error is other situations I have yet to fully understand.

**Comment by jgallowa07** [comment] 2024-07-15 19:40
I'm unable to reproduce this issue on my end. For example, this works just fine for me:

```bash
#!/usr/bin/env bash

for group in sample_ID submitted_by library_batch;
do
        nextflow run matsengrp/phip-flow -r V1.12  \
                --run_zscore_fit_predict true \
                --run_cpm_enr_workflow true \
                --summarize_by_organism true \
                --output_wide_csv true \
                --output_tall_csv false \
                --run_BEER false \
                --peptide_seq_col Prot \
                --peptide_org_col Virus \
                --sample_grouping_col $group \
                --results results/group.${group}.Species."$(date -I)" \
                -profile docker \
                -resume
done
```

@sminot has pointed out that the sample table may have `""` in it rather than a sample name. Is it possible see the contents of `../data-raw/20240216_momi_virscan_allplate_merged_metadata.csv`?

**Comment by jgallowa07** [comment] 2024-07-22 21:08
I'm going to close this issue as I'm only able to re-create via adding empty annotations as suggested above. @bkellman Feel free to re-open if you find this is still occurring after carefully looking at the input tables.

**Closed by jgallowa07** 2024-07-22 21:08 UTC
